### ISSUE TITLE
How to use build?

### ISSUE THREAD

**Issue by blackysky** [PaceCodes/Hyperium#2]
Hi, so I tried **"runClient" in "forgegradle"** and **"jar" in "build"**. It creates a jar, but how i need to use this?
When i put this jar in **"mods" folder**, and launching **Forge 1.8.9**, Minecraft just crashes.

Can you help me? 
If I did something wrong, sorry, this is my first issue...

**Comment by PaceCodes** [comment]
Would it be possible for you to provide me with the crash report so I can assist you further?

**Comment by blackysky** [comment]
> Would it be possible for you to provide me with the crash report so I can assist you further?

I need to put jar in **"mods" folder**?

**Comment by blackysky** [comment]
```
[22:07:22] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:07:22] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:07:22] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[22:07:22] [main/INFO]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[22:07:22] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\Development\Programs\Minecraft\runtime\jre-legacy\windows-x64\jre-legacy
[22:07:23] [main/INFO]: Loading tweaker cc.hyperium.launch.HyperiumTweaker from Hyperium-1.0.jar
[22:07:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:07:23] [main/INFO]: Loading tweak class name cc.hyperium.launch.HyperiumTweaker
[22:07:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:07:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:07:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:07:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:07:23] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:07:23] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:07:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:07:23] [main/INFO]: Calling tweak class cc.hyperium.launch.HyperiumTweaker
[22:07:23] [main/INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[22:07:23] [main/INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[22:07:23] [main/INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[22:07:24] [main/INFO]: [Addons] Loading Addons...
[22:07:24] [main/INFO]: Initialising Bootstraps...
[22:07:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/mods/Hyperium-1.0.jar Service=LaunchWrapper Env=CLIENT
[22:07:24] [main/INFO]: Compatibility level set to JAVA_8
[22:07:24] [main/ERROR]: Mixin config mixins.hyperium.json does not specify "minVersion" property
[22:07:24] [main/INFO]: Starting to load external jars...
[22:07:24] [main/INFO]: Applying transformers...
[22:07:24] [main/ERROR]: Mixin config mixins.hyperium.json does not specify "minVersion" property
[22:07:24] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:07:24] [main/DEBUG]: Loaded 165 rules from AccessTransformer config file forge_at.cfg
[22:07:24] [main/DEBUG]: Validating minecraft
[22:07:24] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:07:24] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[22:07:24] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:07:24] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[22:07:24] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@201aa8c1
[22:07:24] [main/FATAL]: Mixin prepare failed preparing client.MixinClientBrand in mixins.hyperium.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.hyperium.json:client.MixinClientBrand target net.minecraft.client.ClientBrandRetriever was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.hyperium.json:client.MixinClientBrand target net.minecraft.client.ClientBrandRetriever was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:502) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [Hyperium-1.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:07:24] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.hyperium.json:client.MixinClientBrand] from phase [DEFAULT] in config [mixins.hyperium.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[Hyperium-1.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.hyperium.json:client.MixinClientBrand target net.minecraft.client.ClientBrandRetriever was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:502) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[Hyperium-1.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
[22:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[22:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[22:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[22:07:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
This is latest log

**Comment by PaceCodes** [comment]
Did you use gradle build to create the jar file? Instead of the log files, can I get the crash report now?

**Comment by blackysky** [comment]
> Did you use gradle build to create the jar file? Instead of the log files, can I get the crash report now?

If I just use **"Build"** button in IntelliJ IDEA, it says that the build is ready, but build does not appear anywhere. 
But, when I use gradle task, jar is appears, but now working.
And yes, there's **no crash reports**, only logs. 
The **same logs** as I wrote above

**Comment by PaceCodes** [comment]
There must be a crash report if the game crashed or If the crash reports directory does not exist, the game may have crashed of a JVM failure, and one or multiple hs_err_pid#####.log files may be present in the game directory instead.

run your game again then if it crashes.

`Navigate to your game directory as specified in your installation in the Launcher.
On Windows, it is %appdata%\.minecraft\ by default
On macOS, it is ~/Library/Application Support/minecraft by default
On Linux, it is ~/.minecraft by default
Navigate into the crash-reports directory in the game directory
There should be files named like crash-yyyy-mm-dd_hh.mm.ss-(client/server).txt. The crash reports are named by the time of crash, and send that report to me.`

**Comment by PaceCodes** [comment]
try to rerun IntelliJ with the client too

**Comment by blackysky** [comment]
> Должен быть отчет о сбое, если игра вылетела или если каталог отчетов о сбоях не существует, возможно, игра вылетела из-за сбоя JVM, и в каталоге игры могут присутствовать один или несколько файлов журнала hs_err_pid #####. вместо.
> 
> запустите игру еще раз, если она вылетит.
> 
> `Navigate to your game directory as specified in your installation in the Launcher. On Windows, it is %appdata%\.minecraft\ by default On macOS, it is ~/Library/Application Support/minecraft by default On Linux, it is ~/.minecraft by default Navigate into the crash-reports directory in the game directory There should be files named like crash-yyyy-mm-dd_hh.mm.ss-(client/server).txt. The crash reports are named by the time of crash, and send that report to me.`

Bruh, there's **no "hs_err_pid"** in game directory, only the same logs.
I dunno how, but IntelliJ IDEA with **"Minecraft Client" button** launch Minecraft without any crashes.

**Comment by blackysky** [comment]
> > Должен быть отчет о сбое, если игра вылетела или если каталог отчетов о сбоях не существует, возможно, игра вылетела из-за сбоя JVM, и в каталоге игры могут присутствовать один или несколько файлов журнала hs_err_pid #####. вместо.
> > запустите игру еще раз, если она вылетит.
> > `Navigate to your game directory as specified in your installation in the Launcher. On Windows, it is %appdata%\.minecraft\ by default On macOS, it is ~/Library/Application Support/minecraft by default On Linux, it is ~/.minecraft by default Navigate into the crash-reports directory in the game directory There should be files named like crash-yyyy-mm-dd_hh.mm.ss-(client/server).txt. The crash reports are named by the time of crash, and send that report to me.`
> 
> Bruh, there's **no "hs_err_pid"** in game directory, only the same logs.
> I dunno how, but IntelliJ IDEA with **"Minecraft Client" button** launch Minecraft without any crashes.

But launch with random nickname :(

**Comment by PaceCodes** [comment]
In order to play it in Intellij, you'll have to use a session changer and enter your Minecraft credentials

**Comment by blackysky** [comment]
But how can I play not from IntelliJ?
